### PR TITLE
Spellcheck and add GitHub Action for repo

### PR DESCRIPTION
**Pull request by ocaisa**
At the moment your GitHub Action doesn't do anything (it is skipped by default). This version will do a spell check on contributions and also try to build the site. It will also run the lesson checks.

I also fixed the existing spelling typos.

### CODE REVIEW

**Comment by ocaisa** [comment]
See https://github.com/carpentries-incubator/julia-novice/runs/3253449441#check-step-16 for your existing lesson warnings, they are mostly line lengths.

**Comment by BeastyBlacksmith** [comment]
Thats great. Thank you!

**Comment by BeastyBlacksmith** [comment]
@ocaisa unfortunately this workflow is broken now (https://github.com/carpentries-incubator/julia-novice/actions/runs/3575956386)

**Comment by ocaisa** [comment]
@BeastyBlacksmith Problem was not really related to this PR, fixed in #38

**Comment by BeastyBlacksmith** [comment]
@all-contributors add @ocaisa for infra

**Pull request merged**
